namespace imbSCI.Data.enums.fields
{

    /// <summary>
    /// Insert blocks generated by theme
    /// </summary>
    public enum templateFieldTheme
    {
        /// <summary>
        /// CSS links
        /// </summary>
        theme_styles,
        /// <summary>
        /// links for included plugins
        /// </summary>
        theme_plugins,
        /// <summary>
        /// Java script from theme JS template
        /// </summary>
        theme_js
    }
}